version: '3.8'

services:
  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server --requirepass default
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: default
    ports:
      - "6379:6379"

  # SERVIÇO ANTIGO 'postgres' REMOVIDO E 'mysql' ADICIONADO ABAIXO
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Senha do superusuário 'root'
      MYSQL_DATABASE: defaultdb         # Nome do banco de dados a ser criado
      MYSQL_USER: defaultuser           # Nome do usuário a ser criado
      MYSQL_PASSWORD: defaultpassword   # Senha para o usuário 'defaultuser'
    ports:
      - "3306:3306" # Porta padrão do MySQL
    volumes:
      - mysqldata:/var/lib/mysql

  # SERVIÇO ANTIGO 'pgadmin' REMOVIDO E 'adminer' ADICIONADO ABAIXO
  adminer:
    image: adminer:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080" # Acessível em http://localhost:8080 no seu navegador

  waha:
    image: waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:5678/webhook/webhook
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3000:3000"
    depends_on:
      - n8n

  n8n:
    image: n8nio/n8n:latest
    platform: linux/amd64
    environment:
      WEBHOOK_URL: http://host.docker.internal:5678
      N8N_HOST: host.docker.internal
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"

# VOLUMES ATUALIZADOS
volumes:
  mysqldata: # Volume para os dados do MySQL
  waha_sessions:
  waha_media:
  n8n_data: